name: CI

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: ubuntu-latest
        description: The runner to use for the action
      skip_lint:
        type: boolean
        default: false
        description: Whether to skip the lint step
      java_version:
        type: string
        default: '17'
        description: The Java version to use for the action (17, 11, 8, 21)
      distribution:
        type: string
        default: temurin
        description: The distribution to use for setup-java action (temurin, corretto)
      default_bump:
        type: string
        default: patch
        description: The default bump type to use for the action (major, minor, patch)
      github_token:
        type: string
        required: true
        description: The GitHub token to use for the action

jobs:
  maven:
    name: Run Maven CI Pipeline
    uses: vti-do2402/cicd-core/.github/workflows/ci-maven.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      skip_lint: ${{ inputs.skip_lint }}
      java_version: ${{ inputs.java_version }}
      distribution: ${{ inputs.distribution }}

  tag-and-release:
    name: Dry run tag and release
    uses: vti-do2402/cicd-core/.github/workflows/tag-and-release.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      dry_run_tag: true
      draft_release: true
      default_bump: ${{ inputs.default_bump }}
      github_token: ${{ inputs.github_token }}
