name: CI

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: ubuntu-latest
        description: The runner to use for the action
      skip_lint:
        type: boolean
        default: true
        description: Whether to skip the lint step
      java_version:
        type: number
        default: 17
        description: The Java version to use for the action (17, 11, 8, 21)
      distribution:
        type: string
        default: temurin
        description: The distribution to use for setup-java action (temurin, corretto)
      default_bump:
        type: string
        default: patch
        description: The default bump type to use for the action (major, minor, patch)
      github_token:
        type: string
        required: true
        description: The GitHub token to use for the action

jobs:
  ci:
    name: CI
    runs-on: ${{ inputs.runs_on }}
    outputs:
      version: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for Sonar analysis

      - name: Build and Test with Maven
        id: build_and_test
        uses: ./.github/actions/ci/maven
        with:
          skip_lint: ${{ inputs.skip_lint }}
          java_version: ${{ inputs.java_version }}
          distribution: ${{ inputs.distribution }}

      - name: Dry run tag
        id: tag_version
        uses: ./.github/actions/ci/tag-and-release
        with:
          dry_run: true
          draft_release: true
          default_bump: ${{ inputs.default_bump }}
          github_token: ${{ inputs.github_token }}
