name: Deploy

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: mock-project
        description: The runner to use for the action
      environment:
        type: string
        required: true
        default: dev
        description: The environment to push the image to (development, staging, production)
      github_token:
        type: string
        required: true
        description: The GitHub token to use for the action
      default_bump:
        type: string
        default: patch
        description: The default bump type to use for the action (major, minor, patch)
      ecr_repository:
        type: string
        required: true
        description: The repository to push the image to
      docker_build_context:
        type: string
        default: .
        description: The context to build the image in
      dockerfile:
        type: string
        default: Dockerfile
        description: The Dockerfile to use for the image
      image_tag:
        type: string
        required: true
        description: The tag to use for the image
      aws_account_id:
        type: string
        required: true
        description: The AWS account ID to use for the action
      aws_region:
        type: string
        default: us-west-2
        description: The AWS region to use for the action

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ${{ inputs.runs_on }}
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for Sonar analysis

      - name: Tag and Release
        uses: ./.github/actions/ci/tag-and-release
        with:
          github_token: ${{ inputs.github_token }}
          default_bump: ${{ inputs.default_bump }}
          dry_run: false
          draft_release: false

      - name: Deploy
        uses: ./.github/actions/deploy-ecr
        with:
          environment: ${{ inputs.environment }}
          ecr_repository: ${{ inputs.ecr_repository }}
          docker_build_context: ${{ inputs.docker_build_context }}
          dockerfile: ${{ inputs.dockerfile }}
          image_tag: ${{ inputs.image_tag }}
          aws_account_id: ${{ inputs.aws_account_id }}
          aws_region: ${{ inputs.aws_region }}
