name: Deploy

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: mock-project
        description: The runner to use for the action
      java_version:
        type: string
        required: true
        description: The Java version to use for the action
      distribution:
        type: string
        required: true
        description: The distribution to use for the action
      environment:
        type: string
        required: true
        default: dev
        description: The environment to push the image to (development, staging, production)
      github_token:
        type: string
        required: true
        description: The GitHub token to use for the action
      default_bump:
        type: string
        default: patch
        description: The default bump type to use for the action (major, minor, patch)
      ecr_repository:
        type: string
        required: true
        description: The repository to push the image to
      docker_build_context:
        type: string
        default: .
        description: The context to build the image in
      dockerfile:
        type: string
        default: Dockerfile
        description: The Dockerfile to use for the image
      image_tag:
        type: string
        required: true
        description: The tag to use for the image
      aws_account_id:
        type: string
        required: true
        description: The AWS account ID to use for the action
      aws_region:
        type: string
        default: us-west-2
        description: The AWS region to use for the action
    secrets:
      AWS_ACCOUNT_ID:
        required: true
        description: The AWS account ID to use for the action
      AWS_REGION:
        required: true
        description: The AWS region to use for the action
      SONAR_TOKEN:
        required: true
        description: The SonarQube token to use for the action
      SONAR_HOST_URL:
        required: true
        description: The SonarQube host URL to use for the action

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    uses: vti-do2402/cicd-core/.github/workflows/ci-maven.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      java_version: ${{ inputs.java_version }}
      distribution: ${{ inputs.distribution }}
      skip_lint: true # TODO: Remove this
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dry-run-tag-and-release:
    name: Dry run tag and release
    uses: vti-do2402/cicd-core/.github/workflows/tag-and-release.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      dry_run_tag: true
      draft_release: true
      default_bump: ${{ inputs.default_bump }}
      github_token: ${{ inputs.github_token }}

  deploy:
    needs: dry-run-tag-and-release
    uses: vti-do2402/cicd-core/.github/workflows/deploy-ecr.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      environment: ${{ inputs.environment }}
      ecr_repository: ${{ inputs.ecr_repository }}
      image_tag: ${{ needs.dry-run-tag-and-release.outputs.tag-and-release.new_tag }}
      aws_account_id: ${{ inputs.aws_account_id }}
      aws_region: ${{ inputs.aws_region }}
      github_token: ${{ inputs.github_token }}
      default_bump: ${{ inputs.default_bump }}

  tag-and-release:
    name: Dry run tag and release
    needs: [deploy, dry-run-tag-and-release]
    uses: vti-do2402/cicd-core/.github/workflows/tag-and-release.yml@feat/actions
    with:
      runs_on: ${{ inputs.runs_on }}
      dry_run_tag: false
      draft_release: false
      default_bump: ${{ inputs.default_bump }}
      github_token: ${{ inputs.github_token }}

  update-k8s:
    name: Update Kubernetes Manifest
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout cicd-core
        uses: actions/checkout@v4
        with:
          repository: vti-do2402/cicd-core
          token: ${{ inputs.github_token }}
          path: cicd-core
